name: Maven central workflow

on:
  push:
    branches: ['*']
    tags:
      - '[vV][0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  maven:
#   uses: folio-org/.github/.github/workflows/maven.yml@FOLIO-4126-maven-workflows-1
    uses: folio-org/.github/.github/workflows/maven.yml@FOLIO-4126-maven-scratch-1
    secrets: inherit
